### ISSUE TITLE
Ability to remove an array item

### ISSUE THREAD

**Issue by grassick** [bormind/immutable-setter#2]
I've been searching for a lightweight immutability library and the syntax for this is great. Is there a way to remove an array item? If not, could you perhaps suggest a syntax? It's the one piece missing for all basic add/update/remove operations. Thanks!

**Comment by bormind** [comment]
@grassick, thank you for the feedback and for the great suggestion! I will implement _deleteIn()_ function that will work the same way as _setIn()_ but will be responsible for removing specified keyPath element from objects and arrays. I expect to finish it this week and to push update to the npm.

**Comment by grassick** [comment]
Thanks!!
